CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'seguridad') THEN
            CREATE SCHEMA seguridad;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE public.clientes (
        cliente_id integer GENERATED BY DEFAULT AS IDENTITY,
        nombres character varying(100) NOT NULL,
        apellidos character varying(100) NOT NULL,
        dni character varying(8) NOT NULL,
        telefono character varying(15),
        email character varying(150),
        direccion character varying(250),
        fecha_registro timestamp with time zone NOT NULL,
        activo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_clientes" PRIMARY KEY (cliente_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE public.empleados (
        empleado_id integer GENERATED BY DEFAULT AS IDENTITY,
        nombres character varying(100) NOT NULL,
        apellidos character varying(100) NOT NULL,
        dni character varying(8) NOT NULL,
        cargo integer NOT NULL,
        telefono character varying(15),
        email character varying(150) NOT NULL,
        password_hash character varying(256) NOT NULL,
        fecha_contrato timestamp with time zone NOT NULL,
        activo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_empleados" PRIMARY KEY (empleado_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE public.piscinas (
        piscina_id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(100) NOT NULL,
        descripcion character varying(500),
        temperatura_grados numeric(5,2) NOT NULL,
        capacidad_personas integer NOT NULL,
        tarifa_por_hora numeric(10,2) NOT NULL,
        disponible boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_piscinas" PRIMARY KEY (piscina_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE seguridad.roles (
        rol_id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(50) NOT NULL,
        descripcion character varying(200),
        activo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_roles" PRIMARY KEY (rol_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE public."Servicios" (
        "ServicioId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Descripcion" text,
        "Precio" numeric NOT NULL,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_Servicios" PRIMARY KEY ("ServicioId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE public.tipo_servicios (
        tipo_servicio_id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(100) NOT NULL,
        descripcion character varying(500),
        capacidad_maxima integer NOT NULL,
        precio_por_persona numeric(10,2) NOT NULL,
        activo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_tipo_servicios" PRIMARY KEY (tipo_servicio_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE public.reservas (
        reserva_id integer GENERATED BY DEFAULT AS IDENTITY,
        cliente_id integer NOT NULL,
        piscina_id integer NOT NULL,
        fecha_reserva timestamp with time zone NOT NULL,
        fecha_ingreso timestamp with time zone NOT NULL,
        fecha_salida timestamp with time zone NOT NULL,
        numero_personas integer NOT NULL,
        monto_total numeric(10,2) NOT NULL,
        estado integer NOT NULL,
        observaciones character varying(500),
        fecha_creacion timestamp with time zone NOT NULL,
        CONSTRAINT "PK_reservas" PRIMARY KEY (reserva_id),
        CONSTRAINT "FK_reservas_clientes_cliente_id" FOREIGN KEY (cliente_id) REFERENCES public.clientes (cliente_id) ON DELETE CASCADE,
        CONSTRAINT "FK_reservas_piscinas_piscina_id" FOREIGN KEY (piscina_id) REFERENCES public.piscinas (piscina_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE seguridad.usuarios (
        usuario_id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(100) NOT NULL,
        apellido character varying(100) NOT NULL,
        email character varying(150) NOT NULL,
        password_hash character varying(256) NOT NULL,
        rol_id integer NOT NULL,
        activo boolean NOT NULL DEFAULT TRUE,
        fecha_creacion timestamp with time zone NOT NULL,
        CONSTRAINT "PK_usuarios" PRIMARY KEY (usuario_id),
        CONSTRAINT "FK_usuarios_roles_rol_id" FOREIGN KEY (rol_id) REFERENCES seguridad.roles (rol_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE public.aforos (
        aforo_id integer GENERATED BY DEFAULT AS IDENTITY,
        tipo_servicio_id integer NOT NULL,
        fecha timestamp with time zone NOT NULL,
        capacidad_maxima integer NOT NULL,
        ocupacion_actual integer NOT NULL,
        CONSTRAINT "PK_aforos" PRIMARY KEY (aforo_id),
        CONSTRAINT "FK_aforos_tipo_servicios_tipo_servicio_id" FOREIGN KEY (tipo_servicio_id) REFERENCES public.tipo_servicios (tipo_servicio_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE public.pagos (
        pago_id integer GENERATED BY DEFAULT AS IDENTITY,
        reserva_id integer NOT NULL,
        monto numeric(10,2) NOT NULL,
        tipo_pago integer NOT NULL,
        fecha_pago timestamp with time zone NOT NULL,
        numero_comprobante character varying(50),
        observaciones character varying(500),
        CONSTRAINT "PK_pagos" PRIMARY KEY (pago_id),
        CONSTRAINT "FK_pagos_reservas_reserva_id" FOREIGN KEY (reserva_id) REFERENCES public.reservas (reserva_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE public.reserva_servicios (
        reserva_servicio_id integer GENERATED BY DEFAULT AS IDENTITY,
        reserva_id integer NOT NULL,
        servicio_id integer NOT NULL,
        cantidad integer NOT NULL,
        precio_unitario numeric(10,2) NOT NULL,
        CONSTRAINT "PK_reserva_servicios" PRIMARY KEY (reserva_servicio_id),
        CONSTRAINT "FK_reserva_servicios_Servicios_servicio_id" FOREIGN KEY (servicio_id) REFERENCES public."Servicios" ("ServicioId") ON DELETE CASCADE,
        CONSTRAINT "FK_reserva_servicios_reservas_reserva_id" FOREIGN KEY (reserva_id) REFERENCES public.reservas (reserva_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE public.turnos (
        turno_id integer GENERATED BY DEFAULT AS IDENTITY,
        tipo_servicio_id integer NOT NULL,
        fecha_hora timestamp with time zone NOT NULL,
        cantidad_personas integer NOT NULL,
        monto_total numeric(10,2) NOT NULL,
        estado_pago integer NOT NULL,
        metodo_pago integer NOT NULL,
        usuario_id integer NOT NULL,
        fecha_creacion timestamp with time zone NOT NULL,
        CONSTRAINT "PK_turnos" PRIMARY KEY (turno_id),
        CONSTRAINT "FK_turnos_tipo_servicios_tipo_servicio_id" FOREIGN KEY (tipo_servicio_id) REFERENCES public.tipo_servicios (tipo_servicio_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_turnos_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES seguridad.usuarios (usuario_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE TABLE seguridad.usuario_roles (
        usuario_rol_id integer GENERATED BY DEFAULT AS IDENTITY,
        usuario_id integer NOT NULL,
        rol_id integer NOT NULL,
        fecha_asignacion timestamp with time zone NOT NULL,
        CONSTRAINT "PK_usuario_roles" PRIMARY KEY (usuario_rol_id),
        CONSTRAINT "FK_usuario_roles_roles_rol_id" FOREIGN KEY (rol_id) REFERENCES seguridad.roles (rol_id) ON DELETE CASCADE,
        CONSTRAINT "FK_usuario_roles_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES seguridad.usuarios (usuario_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    INSERT INTO seguridad.roles (rol_id, activo, descripcion, nombre)
    VALUES (1, TRUE, 'Acceso total al sistema', 'Administrador');
    INSERT INTO seguridad.roles (rol_id, activo, descripcion, nombre)
    VALUES (2, TRUE, 'Gestión de reservas y pagos', 'Cajero');
    INSERT INTO seguridad.roles (rol_id, activo, descripcion, nombre)
    VALUES (3, TRUE, 'Atención al cliente y reservas', 'Recepcionista');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    INSERT INTO public.tipo_servicios (tipo_servicio_id, activo, capacidad_maxima, descripcion, nombre, precio_por_persona)
    VALUES (1, TRUE, 50, 'Acceso a piscina termal', 'Piscina', 15.0);
    INSERT INTO public.tipo_servicios (tipo_servicio_id, activo, capacidad_maxima, descripcion, nombre, precio_por_persona)
    VALUES (2, TRUE, 4, 'Baño privado con agua termal', 'Baño Privado', 25.0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE UNIQUE INDEX "IX_aforos_tipo_servicio_id_fecha" ON public.aforos (tipo_servicio_id, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE UNIQUE INDEX "IX_clientes_dni" ON public.clientes (dni);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE UNIQUE INDEX "IX_empleados_dni" ON public.empleados (dni);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE UNIQUE INDEX "IX_empleados_email" ON public.empleados (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE UNIQUE INDEX "IX_pagos_reserva_id" ON public.pagos (reserva_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE INDEX "IX_reserva_servicios_reserva_id" ON public.reserva_servicios (reserva_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE INDEX "IX_reserva_servicios_servicio_id" ON public.reserva_servicios (servicio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE INDEX "IX_reservas_cliente_id" ON public.reservas (cliente_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE INDEX "IX_reservas_piscina_id" ON public.reservas (piscina_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE UNIQUE INDEX "IX_roles_nombre" ON seguridad.roles (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE INDEX "IX_turnos_tipo_servicio_id" ON public.turnos (tipo_servicio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE INDEX "IX_turnos_usuario_id" ON public.turnos (usuario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE INDEX "IX_usuario_roles_rol_id" ON seguridad.usuario_roles (rol_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE UNIQUE INDEX "IX_usuario_roles_usuario_id_rol_id" ON seguridad.usuario_roles (usuario_id, rol_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE UNIQUE INDEX "IX_usuarios_email" ON seguridad.usuarios (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    CREATE INDEX "IX_usuarios_rol_id" ON seguridad.usuarios (rol_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    PERFORM setval(
        pg_get_serial_sequence('seguridad.roles', 'rol_id'),
        GREATEST(
            (SELECT MAX(rol_id) FROM seguridad.roles) + 1,
            nextval(pg_get_serial_sequence('seguridad.roles', 'rol_id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('public.tipo_servicios', 'tipo_servicio_id'),
        GREATEST(
            (SELECT MAX(tipo_servicio_id) FROM public.tipo_servicios) + 1,
            nextval(pg_get_serial_sequence('public.tipo_servicios', 'tipo_servicio_id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602151954_BanosTermales') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260602151954_BanosTermales', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'comedor') THEN
            CREATE SCHEMA comedor;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    ALTER TABLE public.piscinas ADD tipo_banio integer NOT NULL DEFAULT 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE TABLE comedor.categorias_menu (
        categoria_menu_id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(100) NOT NULL,
        activo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_categorias_menu" PRIMARY KEY (categoria_menu_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE TABLE public.habitaciones (
        habitacion_id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(100) NOT NULL,
        descripcion character varying(500),
        capacidad integer NOT NULL,
        ocupado boolean NOT NULL DEFAULT FALSE,
        activo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_habitaciones" PRIMARY KEY (habitacion_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE TABLE comedor.mesas (
        mesa_id integer GENERATED BY DEFAULT AS IDENTITY,
        numero integer NOT NULL,
        capacidad integer NOT NULL,
        estado integer NOT NULL,
        activo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_mesas" PRIMARY KEY (mesa_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE TABLE comedor.items_menu (
        item_menu_id integer GENERATED BY DEFAULT AS IDENTITY,
        categoria_menu_id integer NOT NULL,
        nombre character varying(150) NOT NULL,
        descripcion character varying(300),
        precio numeric(10,2) NOT NULL,
        activo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_items_menu" PRIMARY KEY (item_menu_id),
        CONSTRAINT "FK_items_menu_categorias_menu_categoria_menu_id" FOREIGN KEY (categoria_menu_id) REFERENCES comedor.categorias_menu (categoria_menu_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE TABLE comedor.ordenes (
        orden_id integer GENERATED BY DEFAULT AS IDENTITY,
        mesa_id integer NOT NULL,
        usuario_id integer NOT NULL,
        estado integer NOT NULL,
        total numeric(10,2) NOT NULL,
        observaciones character varying(300),
        fecha_apertura timestamp with time zone NOT NULL,
        fecha_cierre timestamp with time zone,
        CONSTRAINT "PK_ordenes" PRIMARY KEY (orden_id),
        CONSTRAINT "FK_ordenes_mesas_mesa_id" FOREIGN KEY (mesa_id) REFERENCES comedor.mesas (mesa_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_ordenes_usuarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES seguridad.usuarios (usuario_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE TABLE comedor.orden_detalles (
        orden_detalle_id integer GENERATED BY DEFAULT AS IDENTITY,
        orden_id integer NOT NULL,
        item_menu_id integer NOT NULL,
        cantidad integer NOT NULL,
        precio_unitario numeric(10,2) NOT NULL,
        estado integer NOT NULL,
        observaciones character varying(300),
        CONSTRAINT "PK_orden_detalles" PRIMARY KEY (orden_detalle_id),
        CONSTRAINT "FK_orden_detalles_items_menu_item_menu_id" FOREIGN KEY (item_menu_id) REFERENCES comedor.items_menu (item_menu_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_orden_detalles_ordenes_orden_id" FOREIGN KEY (orden_id) REFERENCES comedor.ordenes (orden_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE INDEX "IX_items_menu_categoria_menu_id" ON comedor.items_menu (categoria_menu_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE UNIQUE INDEX "IX_mesas_numero" ON comedor.mesas (numero);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE INDEX "IX_orden_detalles_item_menu_id" ON comedor.orden_detalles (item_menu_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE INDEX "IX_orden_detalles_orden_id" ON comedor.orden_detalles (orden_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE INDEX "IX_ordenes_mesa_id" ON comedor.ordenes (mesa_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    CREATE INDEX "IX_ordenes_usuario_id" ON comedor.ordenes (usuario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628060405_AgregarHabitacionYTipoBanio') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260628060405_AgregarHabitacionYTipoBanio', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE seguridad.usuarios ALTER COLUMN fecha_creacion TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE seguridad.usuario_roles ALTER COLUMN fecha_asignacion TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE public.turnos ALTER COLUMN fecha_hora TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE public.turnos ALTER COLUMN fecha_creacion TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE public.reservas ALTER COLUMN fecha_salida TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE public.reservas ALTER COLUMN fecha_reserva TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE public.reservas ALTER COLUMN fecha_ingreso TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE public.reservas ALTER COLUMN fecha_creacion TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE public.pagos ALTER COLUMN fecha_pago TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE comedor.ordenes ALTER COLUMN fecha_cierre TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE comedor.ordenes ALTER COLUMN fecha_apertura TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE public.empleados ALTER COLUMN fecha_contrato TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE public.clientes ALTER COLUMN fecha_registro TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    ALTER TABLE public.aforos ALTER COLUMN fecha TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    CREATE TABLE public.comprobantes (
        comprobante_id integer GENERATED BY DEFAULT AS IDENTITY,
        serie character varying(10) NOT NULL,
        numero integer NOT NULL,
        tipo_ambiente character varying(20) NOT NULL,
        referencia_id integer,
        cliente_dni character varying(20),
        cliente_nombre character varying(200),
        total numeric(10,2) NOT NULL,
        enlace_pdf character varying(500) NOT NULL,
        fecha_emision timestamp without time zone NOT NULL,
        CONSTRAINT "PK_comprobantes" PRIMARY KEY (comprobante_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    CREATE UNIQUE INDEX "IX_comprobantes_serie_numero" ON public.comprobantes (serie, numero);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628191631_AgregarComprobantes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260628191631_AgregarComprobantes', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629035052_ActualizarComprobantes') THEN
    ALTER TABLE public.comprobantes ADD "Cajero" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629035052_ActualizarComprobantes') THEN
    ALTER TABLE public.comprobantes ADD "ClienteRazonSocial" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629035052_ActualizarComprobantes') THEN
    ALTER TABLE public.comprobantes ADD "ClienteRuc" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629035052_ActualizarComprobantes') THEN
    ALTER TABLE public.comprobantes ADD "Estado" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629035052_ActualizarComprobantes') THEN
    ALTER TABLE public.comprobantes ADD "Impuesto" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629035052_ActualizarComprobantes') THEN
    ALTER TABLE public.comprobantes ADD "Local" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629035052_ActualizarComprobantes') THEN
    ALTER TABLE public.comprobantes ADD "Moneda" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629035052_ActualizarComprobantes') THEN
    ALTER TABLE public.comprobantes ADD "TipoComprobante" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629035052_ActualizarComprobantes') THEN
    ALTER TABLE public.comprobantes ADD "TotalGravada" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629035052_ActualizarComprobantes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260629035052_ActualizarComprobantes', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629044725_AgregarTienda') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'tienda') THEN
            CREATE SCHEMA tienda;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629044725_AgregarTienda') THEN
    CREATE TABLE tienda.productos (
        producto_id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(200) NOT NULL,
        descripcion character varying(500),
        codigo_barras character varying(50),
        categoria character varying(100),
        precio numeric(10,2) NOT NULL,
        stock integer NOT NULL DEFAULT 0,
        activo boolean NOT NULL DEFAULT TRUE,
        fecha_registro timestamp without time zone NOT NULL,
        CONSTRAINT "PK_productos" PRIMARY KEY (producto_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629044725_AgregarTienda') THEN
    CREATE UNIQUE INDEX "IX_productos_codigo_barras" ON tienda.productos (codigo_barras) WHERE codigo_barras IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629044725_AgregarTienda') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260629044725_AgregarTienda', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629050503_QuitarCategoriaProducto') THEN
    ALTER TABLE tienda.productos DROP COLUMN categoria;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629050503_QuitarCategoriaProducto') THEN
    UPDATE tienda.productos SET descripcion = '----' WHERE descripcion IS NULL;
    ALTER TABLE tienda.productos ALTER COLUMN descripcion SET NOT NULL;
    ALTER TABLE tienda.productos ALTER COLUMN descripcion SET DEFAULT '----';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629050503_QuitarCategoriaProducto') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260629050503_QuitarCategoriaProducto', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629060734_AgregarInventario') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventario') THEN
            CREATE SCHEMA inventario;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629060734_AgregarInventario') THEN
    ALTER TABLE tienda.productos ADD precio_compra numeric(10,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629060734_AgregarInventario') THEN
    CREATE TABLE inventario.entradas_producto (
        entrada_producto_id integer GENERATED BY DEFAULT AS IDENTITY,
        producto_id integer NOT NULL,
        cantidad integer NOT NULL,
        precio_unitario numeric(10,2) NOT NULL,
        total numeric(12,2) NOT NULL,
        fecha timestamp without time zone NOT NULL,
        observacion character varying(400),
        CONSTRAINT "PK_entradas_producto" PRIMARY KEY (entrada_producto_id),
        CONSTRAINT "FK_entradas_producto_productos_producto_id" FOREIGN KEY (producto_id) REFERENCES tienda.productos (producto_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629060734_AgregarInventario') THEN
    CREATE TABLE inventario.insumos (
        insumo_id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(200) NOT NULL,
        tipo_ambiente character varying(20) NOT NULL,
        tipo_articulo character varying(20) NOT NULL DEFAULT 'insumo',
        unidad character varying(30),
        stock_actual numeric(12,3) NOT NULL DEFAULT 0.0,
        precio_referencia numeric(10,2) NOT NULL DEFAULT 0.0,
        activo boolean NOT NULL DEFAULT TRUE,
        fecha_registro timestamp without time zone NOT NULL,
        CONSTRAINT "PK_insumos" PRIMARY KEY (insumo_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629060734_AgregarInventario') THEN
    CREATE TABLE inventario.entradas_insumo (
        entrada_insumo_id integer GENERATED BY DEFAULT AS IDENTITY,
        insumo_id integer NOT NULL,
        cantidad numeric(12,3) NOT NULL,
        precio_unitario numeric(10,2) NOT NULL,
        total numeric(12,2) NOT NULL,
        fecha timestamp without time zone NOT NULL,
        observacion character varying(400),
        CONSTRAINT "PK_entradas_insumo" PRIMARY KEY (entrada_insumo_id),
        CONSTRAINT "FK_entradas_insumo_insumos_insumo_id" FOREIGN KEY (insumo_id) REFERENCES inventario.insumos (insumo_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629060734_AgregarInventario') THEN
    CREATE INDEX "IX_entradas_insumo_insumo_id" ON inventario.entradas_insumo (insumo_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629060734_AgregarInventario') THEN
    CREATE INDEX "IX_entradas_producto_producto_id" ON inventario.entradas_producto (producto_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629060734_AgregarInventario') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260629060734_AgregarInventario', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629063427_AgregarSalidaInsumo') THEN
    CREATE TABLE inventario.salidas_insumo (
        salida_insumo_id integer GENERATED BY DEFAULT AS IDENTITY,
        insumo_id integer NOT NULL,
        cantidad numeric(12,3) NOT NULL,
        fecha timestamp without time zone NOT NULL DEFAULT (now()),
        observacion character varying(300),
        CONSTRAINT "PK_salidas_insumo" PRIMARY KEY (salida_insumo_id),
        CONSTRAINT "FK_salidas_insumo_insumos_insumo_id" FOREIGN KEY (insumo_id) REFERENCES inventario.insumos (insumo_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629063427_AgregarSalidaInsumo') THEN
    CREATE INDEX "IX_salidas_insumo_insumo_id" ON inventario.salidas_insumo (insumo_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629063427_AgregarSalidaInsumo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260629063427_AgregarSalidaInsumo', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629071943_AgregarModuloCaja') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'caja') THEN
            CREATE SCHEMA caja;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629071943_AgregarModuloCaja') THEN
    CREATE TABLE caja.aperturas_caja (
        apertura_caja_id integer GENERATED BY DEFAULT AS IDENTITY,
        fecha timestamp without time zone NOT NULL,
        monto_inicial numeric(12,2) NOT NULL,
        responsable character varying(150) NOT NULL,
        observaciones character varying(300),
        fecha_registro timestamp without time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_aperturas_caja" PRIMARY KEY (apertura_caja_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629071943_AgregarModuloCaja') THEN
    CREATE TABLE caja.cierres_caja (
        cierre_caja_id integer GENERATED BY DEFAULT AS IDENTITY,
        fecha timestamp without time zone NOT NULL,
        total_sistema numeric(12,2) NOT NULL,
        efectivo_fisico numeric(12,2) NOT NULL,
        yape_fisico numeric(12,2) NOT NULL,
        transferencia_fisico numeric(12,2) NOT NULL,
        total_egresos numeric(12,2) NOT NULL,
        monto_apertura numeric(12,2) NOT NULL,
        diferencia numeric(12,2) NOT NULL,
        observaciones character varying(500),
        encargado_cierre character varying(150) NOT NULL,
        fecha_registro timestamp without time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_cierres_caja" PRIMARY KEY (cierre_caja_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629071943_AgregarModuloCaja') THEN
    CREATE TABLE caja.egresos_caja_chica (
        egreso_caja_chica_id integer GENERATED BY DEFAULT AS IDENTITY,
        fecha timestamp without time zone NOT NULL DEFAULT (now()),
        concepto character varying(200) NOT NULL,
        monto numeric(12,2) NOT NULL,
        responsable character varying(150) NOT NULL,
        tipo_documento character varying(30),
        numero_documento character varying(50),
        registrado_por character varying(150) NOT NULL,
        observaciones character varying(300),
        CONSTRAINT "PK_egresos_caja_chica" PRIMARY KEY (egreso_caja_chica_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629071943_AgregarModuloCaja') THEN
    CREATE INDEX "IX_aperturas_caja_fecha" ON caja.aperturas_caja (fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629071943_AgregarModuloCaja') THEN
    CREATE UNIQUE INDEX "IX_cierres_caja_fecha" ON caja.cierres_caja (fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629071943_AgregarModuloCaja') THEN
    CREATE INDEX "IX_egresos_caja_chica_fecha" ON caja.egresos_caja_chica (fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629071943_AgregarModuloCaja') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260629071943_AgregarModuloCaja', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629215444_AgregarNotaCredito') THEN
    ALTER TABLE public.comprobantes ADD comprobante_origen_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629215444_AgregarNotaCredito') THEN
    CREATE INDEX "IX_comprobantes_comprobante_origen_id" ON public.comprobantes (comprobante_origen_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629215444_AgregarNotaCredito') THEN
    ALTER TABLE public.comprobantes ADD CONSTRAINT "FK_comprobantes_comprobantes_comprobante_origen_id" FOREIGN KEY (comprobante_origen_id) REFERENCES public.comprobantes (comprobante_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629215444_AgregarNotaCredito') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260629215444_AgregarNotaCredito', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701205031_AnulacionConSupervisor') THEN
    ALTER TABLE public.comprobantes ADD autorizado_por character varying(150);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701205031_AnulacionConSupervisor') THEN
    ALTER TABLE public.comprobantes ADD motivo_anulacion character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701205031_AnulacionConSupervisor') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260701205031_AnulacionConSupervisor', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701212449_FlujoAprobacionAnulacion') THEN
    CREATE TABLE public.solicitudes_anulacion (
        solicitud_anulacion_id integer GENERATED BY DEFAULT AS IDENTITY,
        comprobante_id integer NOT NULL,
        motivo character varying(500) NOT NULL,
        solicitado_por character varying(150) NOT NULL,
        estado_anterior_comprobante character varying(50) NOT NULL,
        fecha_solicitud timestamp without time zone NOT NULL,
        estado character varying(20) NOT NULL,
        resuelto_por character varying(150),
        fecha_resolucion timestamp without time zone,
        motivo_rechazo character varying(500),
        CONSTRAINT "PK_solicitudes_anulacion" PRIMARY KEY (solicitud_anulacion_id),
        CONSTRAINT "FK_solicitudes_anulacion_comprobantes_comprobante_id" FOREIGN KEY (comprobante_id) REFERENCES public.comprobantes (comprobante_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701212449_FlujoAprobacionAnulacion') THEN
    CREATE INDEX "IX_solicitudes_anulacion_comprobante_id" ON public.solicitudes_anulacion (comprobante_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701212449_FlujoAprobacionAnulacion') THEN
    CREATE INDEX "IX_solicitudes_anulacion_estado" ON public.solicitudes_anulacion (estado);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701212449_FlujoAprobacionAnulacion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260701212449_FlujoAprobacionAnulacion', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708121451_AgregarPrecioHabitacion') THEN
    ALTER TABLE public.habitaciones ADD precio numeric(10,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708121451_AgregarPrecioHabitacion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260708121451_AgregarPrecioHabitacion', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708124348_AgregarRecetaInsumo') THEN
    CREATE TABLE comedor.receta_insumos (
        receta_insumo_id integer GENERATED BY DEFAULT AS IDENTITY,
        item_menu_id integer NOT NULL,
        insumo_id integer NOT NULL,
        cantidad numeric(12,3) NOT NULL,
        CONSTRAINT "PK_receta_insumos" PRIMARY KEY (receta_insumo_id),
        CONSTRAINT "FK_receta_insumos_insumos_insumo_id" FOREIGN KEY (insumo_id) REFERENCES inventario.insumos (insumo_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_receta_insumos_items_menu_item_menu_id" FOREIGN KEY (item_menu_id) REFERENCES comedor.items_menu (item_menu_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708124348_AgregarRecetaInsumo') THEN
    CREATE INDEX "IX_receta_insumos_insumo_id" ON comedor.receta_insumos (insumo_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708124348_AgregarRecetaInsumo') THEN
    CREATE INDEX "IX_receta_insumos_item_menu_id" ON comedor.receta_insumos (item_menu_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708124348_AgregarRecetaInsumo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260708124348_AgregarRecetaInsumo', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708162305_AgregarProductoAOrdenDetalle') THEN
    ALTER TABLE comedor.orden_detalles ALTER COLUMN item_menu_id DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708162305_AgregarProductoAOrdenDetalle') THEN
    ALTER TABLE comedor.orden_detalles ADD producto_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708162305_AgregarProductoAOrdenDetalle') THEN
    CREATE INDEX "IX_orden_detalles_producto_id" ON comedor.orden_detalles (producto_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708162305_AgregarProductoAOrdenDetalle') THEN
    ALTER TABLE comedor.orden_detalles ADD CONSTRAINT "CK_orden_detalles_item_o_producto" CHECK ((item_menu_id IS NOT NULL AND producto_id IS NULL) OR (item_menu_id IS NULL AND producto_id IS NOT NULL));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708162305_AgregarProductoAOrdenDetalle') THEN
    ALTER TABLE comedor.orden_detalles ADD CONSTRAINT "FK_orden_detalles_productos_producto_id" FOREIGN KEY (producto_id) REFERENCES tienda.productos (producto_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708162305_AgregarProductoAOrdenDetalle') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260708162305_AgregarProductoAOrdenDetalle', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710035346_AgregarRolesModulos_CheckInOut_UsuarioEmpleado') THEN
    ALTER TABLE seguridad.usuarios ADD empleado_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710035346_AgregarRolesModulos_CheckInOut_UsuarioEmpleado') THEN
    ALTER TABLE public.habitaciones ADD fecha_check_in timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710035346_AgregarRolesModulos_CheckInOut_UsuarioEmpleado') THEN
    ALTER TABLE public.habitaciones ADD fecha_check_out timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710035346_AgregarRolesModulos_CheckInOut_UsuarioEmpleado') THEN
    CREATE UNIQUE INDEX "IX_usuarios_empleado_id" ON seguridad.usuarios (empleado_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710035346_AgregarRolesModulos_CheckInOut_UsuarioEmpleado') THEN
    ALTER TABLE seguridad.usuarios ADD CONSTRAINT "FK_usuarios_empleados_empleado_id" FOREIGN KEY (empleado_id) REFERENCES public.empleados (empleado_id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710035346_AgregarRolesModulos_CheckInOut_UsuarioEmpleado') THEN

                    UPDATE seguridad.roles SET descripcion = 'Baños Termales, Habitaciones, Tienda, Caja, Inventario y Comedor (mesas/categorías/menú)' WHERE rol_id = 1;
                    UPDATE seguridad.roles SET nombre = 'Mozo', descripcion = 'Operación de comedor desde la app móvil (mesas, órdenes)' WHERE rol_id = 2;
                    UPDATE seguridad.roles SET descripcion = 'Baños Termales y Habitaciones (check-in/check-out)' WHERE rol_id = 3;
                    UPDATE seguridad.roles SET descripcion = 'Acceso total al sistema' WHERE rol_id = 4;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710035346_AgregarRolesModulos_CheckInOut_UsuarioEmpleado') THEN
    UPDATE seguridad.usuarios SET rol_id = 4 WHERE rol_id = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710035346_AgregarRolesModulos_CheckInOut_UsuarioEmpleado') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260710035346_AgregarRolesModulos_CheckInOut_UsuarioEmpleado', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE seguridad.usuarios DROP CONSTRAINT "FK_usuarios_empleados_empleado_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    DROP INDEX public."IX_empleados_email";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE seguridad.usuarios DROP COLUMN apellido;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE seguridad.usuarios DROP COLUMN nombre;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE public.empleados DROP COLUMN cargo;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE public.empleados DROP COLUMN email;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE public.empleados DROP COLUMN fecha_contrato;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE public.empleados DROP COLUMN password_hash;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE public.empleados DROP COLUMN telefono;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'compras') THEN
            CREATE SCHEMA compras;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN

                    INSERT INTO public.empleados (nombres, apellidos, dni, activo)
                    SELECT 'Sistema', 'Administrador', '00000000', true
                    WHERE NOT EXISTS (SELECT 1 FROM public.empleados WHERE dni = '00000000');

                    UPDATE seguridad.usuarios
                    SET empleado_id = (SELECT empleado_id FROM public.empleados WHERE dni = '00000000')
                    WHERE empleado_id IS NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    UPDATE seguridad.usuarios SET empleado_id = 0 WHERE empleado_id IS NULL;
    ALTER TABLE seguridad.usuarios ALTER COLUMN empleado_id SET NOT NULL;
    ALTER TABLE seguridad.usuarios ALTER COLUMN empleado_id SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE inventario.entradas_producto ADD compra_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE inventario.entradas_insumo ADD compra_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    CREATE TABLE compras.proveedores (
        proveedor_id integer GENERATED BY DEFAULT AS IDENTITY,
        ruc character varying(11) NOT NULL,
        razon_social character varying(200) NOT NULL,
        nombre_comercial character varying(200),
        direccion character varying(300),
        telefono character varying(15),
        email character varying(150),
        activo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_proveedores" PRIMARY KEY (proveedor_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    CREATE TABLE compras.compras (
        compra_id integer GENERATED BY DEFAULT AS IDENTITY,
        proveedor_id integer NOT NULL,
        tipo_comprobante character varying(20) NOT NULL,
        serie character varying(10) NOT NULL,
        numero integer NOT NULL,
        fecha_emision timestamp without time zone NOT NULL,
        forma_pago character varying(20) NOT NULL,
        fecha_vencimiento timestamp without time zone,
        moneda character varying(3) NOT NULL DEFAULT 'PEN',
        total_gravada numeric(10,2) NOT NULL,
        igv numeric(10,2) NOT NULL,
        total numeric(10,2) NOT NULL,
        estado character varying(20) NOT NULL,
        observaciones character varying(400),
        registrado_por character varying(150) NOT NULL,
        fecha_registro timestamp without time zone NOT NULL DEFAULT (now()),
        fecha_pago timestamp without time zone,
        egreso_caja_chica_id integer,
        CONSTRAINT "PK_compras" PRIMARY KEY (compra_id),
        CONSTRAINT "FK_compras_egresos_caja_chica_egreso_caja_chica_id" FOREIGN KEY (egreso_caja_chica_id) REFERENCES caja.egresos_caja_chica (egreso_caja_chica_id) ON DELETE SET NULL,
        CONSTRAINT "FK_compras_proveedores_proveedor_id" FOREIGN KEY (proveedor_id) REFERENCES compras.proveedores (proveedor_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    CREATE TABLE compras.detalle_compras (
        detalle_compra_id integer GENERATED BY DEFAULT AS IDENTITY,
        compra_id integer NOT NULL,
        tipo_item character varying(20) NOT NULL,
        insumo_id integer,
        producto_id integer,
        cantidad numeric(12,3) NOT NULL,
        precio_unitario numeric(10,2) NOT NULL,
        total numeric(10,2) NOT NULL,
        CONSTRAINT "PK_detalle_compras" PRIMARY KEY (detalle_compra_id),
        CONSTRAINT "CK_detalle_compras_insumo_o_producto" CHECK ((insumo_id IS NOT NULL AND producto_id IS NULL) OR (insumo_id IS NULL AND producto_id IS NOT NULL)),
        CONSTRAINT "FK_detalle_compras_compras_compra_id" FOREIGN KEY (compra_id) REFERENCES compras.compras (compra_id) ON DELETE CASCADE,
        CONSTRAINT "FK_detalle_compras_insumos_insumo_id" FOREIGN KEY (insumo_id) REFERENCES inventario.insumos (insumo_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_detalle_compras_productos_producto_id" FOREIGN KEY (producto_id) REFERENCES tienda.productos (producto_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    CREATE INDEX "IX_entradas_producto_compra_id" ON inventario.entradas_producto (compra_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    CREATE INDEX "IX_entradas_insumo_compra_id" ON inventario.entradas_insumo (compra_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    CREATE INDEX "IX_compras_egreso_caja_chica_id" ON compras.compras (egreso_caja_chica_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    CREATE UNIQUE INDEX "IX_compras_proveedor_id_serie_numero" ON compras.compras (proveedor_id, serie, numero);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    CREATE INDEX "IX_detalle_compras_compra_id" ON compras.detalle_compras (compra_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    CREATE INDEX "IX_detalle_compras_insumo_id" ON compras.detalle_compras (insumo_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    CREATE INDEX "IX_detalle_compras_producto_id" ON compras.detalle_compras (producto_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    CREATE UNIQUE INDEX "IX_proveedores_ruc" ON compras.proveedores (ruc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE inventario.entradas_insumo ADD CONSTRAINT "FK_entradas_insumo_compras_compra_id" FOREIGN KEY (compra_id) REFERENCES compras.compras (compra_id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE inventario.entradas_producto ADD CONSTRAINT "FK_entradas_producto_compras_compra_id" FOREIGN KEY (compra_id) REFERENCES compras.compras (compra_id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    ALTER TABLE seguridad.usuarios ADD CONSTRAINT "FK_usuarios_empleados_empleado_id" FOREIGN KEY (empleado_id) REFERENCES public.empleados (empleado_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711022511_EmpleadoUsuarioRefactor') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260711022511_EmpleadoUsuarioRefactor', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711030941_AgregarFiadoAComprobante') THEN
    ALTER TABLE public.comprobantes ADD cliente_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711030941_AgregarFiadoAComprobante') THEN
    ALTER TABLE public.comprobantes ADD cobrado boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711030941_AgregarFiadoAComprobante') THEN
    ALTER TABLE public.comprobantes ADD fecha_cobro timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711030941_AgregarFiadoAComprobante') THEN
    ALTER TABLE public.comprobantes ADD metodo_pago integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711030941_AgregarFiadoAComprobante') THEN
    CREATE INDEX "IX_comprobantes_cliente_id" ON public.comprobantes (cliente_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711030941_AgregarFiadoAComprobante') THEN
    ALTER TABLE public.comprobantes ADD CONSTRAINT "FK_comprobantes_clientes_cliente_id" FOREIGN KEY (cliente_id) REFERENCES public.clientes (cliente_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711030941_AgregarFiadoAComprobante') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260711030941_AgregarFiadoAComprobante', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711031049_FijarDefaultMetodoPago') THEN
    UPDATE public.comprobantes SET metodo_pago = 1 WHERE metodo_pago = 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711031049_FijarDefaultMetodoPago') THEN
    ALTER TABLE public.comprobantes ALTER COLUMN metodo_pago SET DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711031049_FijarDefaultMetodoPago') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260711031049_FijarDefaultMetodoPago', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711031558_AgregarComprobanteAOrdenDetalle') THEN
    ALTER TABLE comedor.orden_detalles ADD comprobante_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711031558_AgregarComprobanteAOrdenDetalle') THEN
    CREATE INDEX "IX_orden_detalles_comprobante_id" ON comedor.orden_detalles (comprobante_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711031558_AgregarComprobanteAOrdenDetalle') THEN
    ALTER TABLE comedor.orden_detalles ADD CONSTRAINT "FK_orden_detalles_comprobantes_comprobante_id" FOREIGN KEY (comprobante_id) REFERENCES public.comprobantes (comprobante_id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711031558_AgregarComprobanteAOrdenDetalle') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260711031558_AgregarComprobanteAOrdenDetalle', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711045917_AgregarPaquetesBanio') THEN
    CREATE TABLE public.paquetes_banio (
        paquete_banio_id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(100) NOT NULL,
        precio numeric(10,2) NOT NULL,
        activo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_paquetes_banio" PRIMARY KEY (paquete_banio_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711045917_AgregarPaquetesBanio') THEN
    CREATE TABLE public.paquete_banio_tipo_servicios (
        paquete_banio_id integer NOT NULL,
        tipo_servicio_id integer NOT NULL,
        CONSTRAINT "PK_paquete_banio_tipo_servicios" PRIMARY KEY (paquete_banio_id, tipo_servicio_id),
        CONSTRAINT "FK_paquete_banio_tipo_servicios_paquetes_banio_paquete_banio_id" FOREIGN KEY (paquete_banio_id) REFERENCES public.paquetes_banio (paquete_banio_id) ON DELETE CASCADE,
        CONSTRAINT "FK_paquete_banio_tipo_servicios_tipo_servicios_tipo_servicio_id" FOREIGN KEY (tipo_servicio_id) REFERENCES public.tipo_servicios (tipo_servicio_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711045917_AgregarPaquetesBanio') THEN
    UPDATE public.tipo_servicios SET precio_por_persona = 5.0
    WHERE tipo_servicio_id = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711045917_AgregarPaquetesBanio') THEN
    UPDATE public.tipo_servicios SET precio_por_persona = 5.0
    WHERE tipo_servicio_id = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711045917_AgregarPaquetesBanio') THEN
    CREATE INDEX "IX_paquete_banio_tipo_servicios_tipo_servicio_id" ON public.paquete_banio_tipo_servicios (tipo_servicio_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711045917_AgregarPaquetesBanio') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260711045917_AgregarPaquetesBanio', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711050328_AgregarComprobanteDetalle') THEN
    CREATE TABLE public.comprobante_detalles (
        comprobante_detalle_id integer GENERATED BY DEFAULT AS IDENTITY,
        comprobante_id integer NOT NULL,
        descripcion character varying(300) NOT NULL,
        cantidad integer NOT NULL,
        precio_unitario numeric(10,2) NOT NULL,
        subtotal numeric(10,2) NOT NULL,
        CONSTRAINT "PK_comprobante_detalles" PRIMARY KEY (comprobante_detalle_id),
        CONSTRAINT "FK_comprobante_detalles_comprobantes_comprobante_id" FOREIGN KEY (comprobante_id) REFERENCES public.comprobantes (comprobante_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711050328_AgregarComprobanteDetalle') THEN
    CREATE INDEX "IX_comprobante_detalles_comprobante_id" ON public.comprobante_detalles (comprobante_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711050328_AgregarComprobanteDetalle') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260711050328_AgregarComprobanteDetalle', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711075016_AgregarStockMinimo') THEN
    ALTER TABLE tienda.productos ADD stock_minimo integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711075016_AgregarStockMinimo') THEN
    ALTER TABLE inventario.insumos ADD stock_minimo numeric(12,3) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711075016_AgregarStockMinimo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260711075016_AgregarStockMinimo', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260712130129_ProveedorOpcionalEnCompras') THEN
    ALTER TABLE compras.compras ALTER COLUMN proveedor_id DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260712130129_ProveedorOpcionalEnCompras') THEN
    ALTER TABLE compras.compras ADD nombre_proveedor_manual character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260712130129_ProveedorOpcionalEnCompras') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260712130129_ProveedorOpcionalEnCompras', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713060031_AgregarMotivoCancelacionOrden') THEN
    ALTER TABLE comedor.ordenes ADD motivo_cancelacion character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713060031_AgregarMotivoCancelacionOrden') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260713060031_AgregarMotivoCancelacionOrden', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713114519_AgregarHabitacionItems') THEN
    CREATE TABLE public.habitacion_items (
        habitacion_item_id integer GENERATED BY DEFAULT AS IDENTITY,
        habitacion_id integer NOT NULL,
        nombre character varying(100) NOT NULL,
        cantidad integer NOT NULL DEFAULT 1,
        CONSTRAINT "PK_habitacion_items" PRIMARY KEY (habitacion_item_id),
        CONSTRAINT "FK_habitacion_items_habitaciones_habitacion_id" FOREIGN KEY (habitacion_id) REFERENCES public.habitaciones (habitacion_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713114519_AgregarHabitacionItems') THEN
    CREATE INDEX "IX_habitacion_items_habitacion_id" ON public.habitacion_items (habitacion_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713114519_AgregarHabitacionItems') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260713114519_AgregarHabitacionItems', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713122900_SerieNumeroOpcionalEnCompras') THEN
    ALTER TABLE compras.compras ALTER COLUMN serie DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713122900_SerieNumeroOpcionalEnCompras') THEN
    ALTER TABLE compras.compras ALTER COLUMN numero DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713122900_SerieNumeroOpcionalEnCompras') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260713122900_SerieNumeroOpcionalEnCompras', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713131342_UnirMesasYPedidosLlevar') THEN
    ALTER TABLE comedor.ordenes ALTER COLUMN mesa_id DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713131342_UnirMesasYPedidosLlevar') THEN
    ALTER TABLE comedor.ordenes ADD tipo_entrega character varying(20) NOT NULL DEFAULT 'comedor';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713131342_UnirMesasYPedidosLlevar') THEN
    ALTER TABLE comedor.mesas ADD mesa_principal_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713131342_UnirMesasYPedidosLlevar') THEN
    CREATE INDEX "IX_mesas_mesa_principal_id" ON comedor.mesas (mesa_principal_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713131342_UnirMesasYPedidosLlevar') THEN
    ALTER TABLE comedor.mesas ADD CONSTRAINT "FK_mesas_mesas_mesa_principal_id" FOREIGN KEY (mesa_principal_id) REFERENCES comedor.mesas (mesa_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713131342_UnirMesasYPedidosLlevar') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260713131342_UnirMesasYPedidosLlevar', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714194747_AgregarComprobanteSunatYSeries') THEN
    CREATE TABLE public.comprobante_series (
        serie character varying(10) NOT NULL,
        tipo_comprobante character varying(5) NOT NULL,
        ultimo_numero integer NOT NULL,
        CONSTRAINT "PK_comprobante_series" PRIMARY KEY (serie)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714194747_AgregarComprobanteSunatYSeries') THEN
    CREATE TABLE public.comprobantes_sunat (
        comprobante_id integer NOT NULL,
        xml_firmado text NOT NULL,
        hash_digest_value character varying(100),
        cdr_xml text,
        cdr_codigo_respuesta integer,
        cdr_descripcion character varying(500),
        observaciones_sunat text,
        estado integer NOT NULL DEFAULT 0,
        intentos_envio integer NOT NULL DEFAULT 0,
        fecha_limite_envio timestamp without time zone NOT NULL,
        fecha_envio_sunat timestamp without time zone,
        ticket_resumen character varying(50),
        CONSTRAINT "PK_comprobantes_sunat" PRIMARY KEY (comprobante_id),
        CONSTRAINT "FK_comprobantes_sunat_comprobantes_comprobante_id" FOREIGN KEY (comprobante_id) REFERENCES public.comprobantes (comprobante_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714194747_AgregarComprobanteSunatYSeries') THEN

                    INSERT INTO public.comprobante_series (serie, tipo_comprobante, ultimo_numero)
                    SELECT serie, "TipoComprobante", MAX(numero)
                    FROM public.comprobantes
                    GROUP BY serie, "TipoComprobante"
                    ON CONFLICT (serie) DO NOTHING;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260714194747_AgregarComprobanteSunatYSeries') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260714194747_AgregarComprobanteSunatYSeries', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715030647_AgregarCodigoMotivoNc') THEN
    ALTER TABLE public.comprobantes ADD codigo_motivo_nc character varying(2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715030647_AgregarCodigoMotivoNc') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260715030647_AgregarCodigoMotivoNc', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715041542_AgregarNotaCreditoASolicitudAnulacion') THEN
    ALTER TABLE public.solicitudes_anulacion ADD nota_credito_comprobante_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715041542_AgregarNotaCreditoASolicitudAnulacion') THEN
    CREATE INDEX "IX_solicitudes_anulacion_nota_credito_comprobante_id" ON public.solicitudes_anulacion (nota_credito_comprobante_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715041542_AgregarNotaCreditoASolicitudAnulacion') THEN
    ALTER TABLE public.solicitudes_anulacion ADD CONSTRAINT "FK_solicitudes_anulacion_comprobantes_nota_credito_comprobante~" FOREIGN KEY (nota_credito_comprobante_id) REFERENCES public.comprobantes (comprobante_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715041542_AgregarNotaCreditoASolicitudAnulacion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260715041542_AgregarNotaCreditoASolicitudAnulacion', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715085212_AgregarMontoEfectivoMixto') THEN
    ALTER TABLE public.comprobantes ADD monto_efectivo_mixto numeric(10,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715085212_AgregarMontoEfectivoMixto') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260715085212_AgregarMontoEfectivoMixto', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201226_AgregarDesgloseSistemaCierreCaja') THEN
    ALTER TABLE caja.cierres_caja ADD efectivo_sistema numeric(12,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201226_AgregarDesgloseSistemaCierreCaja') THEN
    ALTER TABLE caja.cierres_caja ADD yape_sistema numeric(12,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201226_AgregarDesgloseSistemaCierreCaja') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260715201226_AgregarDesgloseSistemaCierreCaja', '8.0.11');
    END IF;
END $EF$;
COMMIT;

