// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Termales.DAL.Context;

#nullable disable

namespace Termales.DAL.Migrations
{
    [DbContext(typeof(TermalesDbContext))]
    [Migration("20260602151954_BanosTermales")]
    partial class BanosTermales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Termales.Entities.Models.Aforo", b =>
                {
                    b.Property<int>("AforoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("aforo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AforoId"));

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_maxima");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("OcupacionActual")
                        .HasColumnType("integer")
                        .HasColumnName("ocupacion_actual");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_servicio_id");

                    b.HasKey("AforoId");

                    b.HasIndex("TipoServicioId", "Fecha")
                        .IsUnique();

                    b.ToTable("aforos", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefono");

                    b.HasKey("ClienteId");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("clientes", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("empleado_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<int>("Cargo")
                        .HasColumnType("integer")
                        .HasColumnName("cargo");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaContrato")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_contrato");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefono");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("empleados", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pago_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoId"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_comprobante");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer")
                        .HasColumnName("reserva_id");

                    b.Property<int>("TipoPago")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_pago");

                    b.HasKey("PagoId");

                    b.HasIndex("ReservaId")
                        .IsUnique();

                    b.ToTable("pagos", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Piscina", b =>
                {
                    b.Property<int>("PiscinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("piscina_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PiscinaId"));

                    b.Property<int>("CapacidadPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_personas");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("TarifaPorHora")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tarifa_por_hora");

                    b.Property<decimal>("TemperaturaGrados")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("temperatura_grados");

                    b.HasKey("PiscinaId");

                    b.ToTable("piscinas", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reserva_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_reserva");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_salida");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_total");

                    b.Property<int>("NumeroPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_personas");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int>("PiscinaId")
                        .HasColumnType("integer")
                        .HasColumnName("piscina_id");

                    b.HasKey("ReservaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PiscinaId");

                    b.ToTable("reservas", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.ReservaServicio", b =>
                {
                    b.Property<int>("ReservaServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reserva_servicio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservaServicioId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer")
                        .HasColumnName("reserva_id");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("servicio_id");

                    b.HasKey("ReservaServicioId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("ServicioId");

                    b.ToTable("reserva_servicios", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", "seguridad");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Activo = true,
                            Descripcion = "Acceso total al sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            RolId = 2,
                            Activo = true,
                            Descripcion = "Gestión de reservas y pagos",
                            Nombre = "Cajero"
                        },
                        new
                        {
                            RolId = 3,
                            Activo = true,
                            Descripcion = "Atención al cliente y reservas",
                            Nombre = "Recepcionista"
                        });
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("usuarios", "seguridad");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioRolId"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("UsuarioRolId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique();

                    b.ToTable("usuario_roles", "seguridad");
                });

            modelBuilder.Entity("Termales.Entities.Models.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServicioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("ServicioId");

                    b.ToTable("Servicios", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.TipoServicio", b =>
                {
                    b.Property<int>("TipoServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipo_servicio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoServicioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_maxima");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioPorPersona")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_por_persona");

                    b.HasKey("TipoServicioId");

                    b.ToTable("tipo_servicios", "public");

                    b.HasData(
                        new
                        {
                            TipoServicioId = 1,
                            Activo = true,
                            CapacidadMaxima = 50,
                            Descripcion = "Acceso a piscina termal",
                            Nombre = "Piscina",
                            PrecioPorPersona = 15.00m
                        },
                        new
                        {
                            TipoServicioId = 2,
                            Activo = true,
                            CapacidadMaxima = 4,
                            Descripcion = "Baño privado con agua termal",
                            Nombre = "Baño Privado",
                            PrecioPorPersona = 25.00m
                        });
                });

            modelBuilder.Entity("Termales.Entities.Models.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("turno_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TurnoId"));

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_personas");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("integer")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_total");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_servicio_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("TurnoId");

                    b.HasIndex("TipoServicioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("turnos", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Aforo", b =>
                {
                    b.HasOne("Termales.Entities.Models.TipoServicio", "TipoServicio")
                        .WithMany("Aforos")
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("Termales.Entities.Models.Pago", b =>
                {
                    b.HasOne("Termales.Entities.Models.Reserva", "Reserva")
                        .WithOne("Pago")
                        .HasForeignKey("Termales.Entities.Models.Pago", "ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Termales.Entities.Models.Reserva", b =>
                {
                    b.HasOne("Termales.Entities.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Termales.Entities.Models.Piscina", "Piscina")
                        .WithMany("Reservas")
                        .HasForeignKey("PiscinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Piscina");
                });

            modelBuilder.Entity("Termales.Entities.Models.ReservaServicio", b =>
                {
                    b.HasOne("Termales.Entities.Models.Reserva", "Reserva")
                        .WithMany("ReservaServicios")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Termales.Entities.Models.Servicio", "Servicio")
                        .WithMany("ReservaServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.Usuario", b =>
                {
                    b.HasOne("Termales.Entities.Models.Seguridad.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.UsuarioRol", b =>
                {
                    b.HasOne("Termales.Entities.Models.Seguridad.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Termales.Entities.Models.Seguridad.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Termales.Entities.Models.Turno", b =>
                {
                    b.HasOne("Termales.Entities.Models.TipoServicio", "TipoServicio")
                        .WithMany("Turnos")
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Termales.Entities.Models.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoServicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Termales.Entities.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Termales.Entities.Models.Piscina", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Termales.Entities.Models.Reserva", b =>
                {
                    b.Navigation("Pago");

                    b.Navigation("ReservaServicios");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Termales.Entities.Models.Servicio", b =>
                {
                    b.Navigation("ReservaServicios");
                });

            modelBuilder.Entity("Termales.Entities.Models.TipoServicio", b =>
                {
                    b.Navigation("Aforos");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
