// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Termales.DAL.Context;

#nullable disable

namespace Termales.DAL.Migrations
{
    [DbContext(typeof(TermalesDbContext))]
    [Migration("20260629063427_AgregarSalidaInsumo")]
    partial class AgregarSalidaInsumo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Termales.Entities.Models.Aforo", b =>
                {
                    b.Property<int>("AforoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("aforo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AforoId"));

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_maxima");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("OcupacionActual")
                        .HasColumnType("integer")
                        .HasColumnName("ocupacion_actual");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_servicio_id");

                    b.HasKey("AforoId");

                    b.HasIndex("TipoServicioId", "Fecha")
                        .IsUnique();

                    b.ToTable("aforos", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefono");

                    b.HasKey("ClienteId");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("clientes", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.CategoriaMenu", b =>
                {
                    b.Property<int>("CategoriaMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categoria_menu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaMenuId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("CategoriaMenuId");

                    b.ToTable("categorias_menu", "comedor");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.ItemMenu", b =>
                {
                    b.Property<int>("ItemMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_menu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemMenuId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CategoriaMenuId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_menu_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("ItemMenuId");

                    b.HasIndex("CategoriaMenuId");

                    b.ToTable("items_menu", "comedor");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mesa_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MesaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.HasKey("MesaId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("mesas", "comedor");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.Orden", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orden_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdenId"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer")
                        .HasColumnName("mesa_id");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("OrdenId");

                    b.HasIndex("MesaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ordenes", "comedor");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.OrdenDetalle", b =>
                {
                    b.Property<int>("OrdenDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orden_detalle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdenDetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("ItemMenuId")
                        .HasColumnType("integer")
                        .HasColumnName("item_menu_id");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observaciones");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("OrdenDetalleId");

                    b.HasIndex("ItemMenuId");

                    b.HasIndex("OrdenId");

                    b.ToTable("orden_detalles", "comedor");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comprobante", b =>
                {
                    b.Property<int>("ComprobanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("comprobante_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComprobanteId"));

                    b.Property<string>("Cajero")
                        .HasColumnType("text");

                    b.Property<string>("ClienteDni")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cliente_dni");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente_nombre");

                    b.Property<string>("ClienteRazonSocial")
                        .HasColumnType("text");

                    b.Property<string>("ClienteRuc")
                        .HasColumnType("text");

                    b.Property<string>("EnlacePdf")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("enlace_pdf");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("numeric");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("referencia_id");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("serie");

                    b.Property<string>("TipoAmbiente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_ambiente");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalGravada")
                        .HasColumnType("numeric");

                    b.HasKey("ComprobanteId");

                    b.HasIndex("Serie", "Numero")
                        .IsUnique();

                    b.ToTable("comprobantes", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("empleado_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<int>("Cargo")
                        .HasColumnType("integer")
                        .HasColumnName("cargo");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaContrato")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_contrato");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefono");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("empleados", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Habitacion", b =>
                {
                    b.Property<int>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("habitacion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HabitacionId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<bool>("Ocupado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ocupado");

                    b.HasKey("HabitacionId");

                    b.ToTable("habitaciones", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Inventario.EntradaInsumo", b =>
                {
                    b.Property<int>("EntradaInsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entrada_insumo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntradaInsumoId"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("insumo_id");

                    b.Property<string>("Observacion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("observacion");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.HasKey("EntradaInsumoId");

                    b.HasIndex("InsumoId");

                    b.ToTable("entradas_insumo", "inventario");
                });

            modelBuilder.Entity("Termales.Entities.Models.Inventario.EntradaProducto", b =>
                {
                    b.Property<int>("EntradaProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entrada_producto_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntradaProductoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Observacion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("observacion");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.HasKey("EntradaProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("entradas_producto", "inventario");
                });

            modelBuilder.Entity("Termales.Entities.Models.Inventario.Insumo", b =>
                {
                    b.Property<int>("InsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("insumo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InsumoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioReferencia")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_referencia");

                    b.Property<decimal>("StockActual")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("stock_actual");

                    b.Property<string>("TipoAmbiente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_ambiente");

                    b.Property<string>("TipoArticulo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("insumo")
                        .HasColumnName("tipo_articulo");

                    b.Property<string>("Unidad")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unidad");

                    b.HasKey("InsumoId");

                    b.ToTable("insumos", "inventario");
                });

            modelBuilder.Entity("Termales.Entities.Models.Inventario.SalidaInsumo", b =>
                {
                    b.Property<int>("SalidaInsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("salida_insumo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalidaInsumoId"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("insumo_id");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacion");

                    b.HasKey("SalidaInsumoId");

                    b.HasIndex("InsumoId");

                    b.ToTable("salidas_insumo", "inventario");
                });

            modelBuilder.Entity("Termales.Entities.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pago_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoId"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_comprobante");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer")
                        .HasColumnName("reserva_id");

                    b.Property<int>("TipoPago")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_pago");

                    b.HasKey("PagoId");

                    b.HasIndex("ReservaId")
                        .IsUnique();

                    b.ToTable("pagos", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Piscina", b =>
                {
                    b.Property<int>("PiscinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("piscina_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PiscinaId"));

                    b.Property<int>("CapacidadPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_personas");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("TarifaPorHora")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tarifa_por_hora");

                    b.Property<decimal>("TemperaturaGrados")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("temperatura_grados");

                    b.Property<int>("TipoBanio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("tipo_banio");

                    b.HasKey("PiscinaId");

                    b.ToTable("piscinas", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reserva_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_reserva");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_salida");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_total");

                    b.Property<int>("NumeroPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_personas");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int>("PiscinaId")
                        .HasColumnType("integer")
                        .HasColumnName("piscina_id");

                    b.HasKey("ReservaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PiscinaId");

                    b.ToTable("reservas", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.ReservaServicio", b =>
                {
                    b.Property<int>("ReservaServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reserva_servicio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservaServicioId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer")
                        .HasColumnName("reserva_id");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("servicio_id");

                    b.HasKey("ReservaServicioId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("ServicioId");

                    b.ToTable("reserva_servicios", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", "seguridad");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Activo = true,
                            Descripcion = "Acceso total al sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            RolId = 2,
                            Activo = true,
                            Descripcion = "Gestión de reservas y pagos",
                            Nombre = "Cajero"
                        },
                        new
                        {
                            RolId = 3,
                            Activo = true,
                            Descripcion = "Atención al cliente y reservas",
                            Nombre = "Recepcionista"
                        });
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("usuarios", "seguridad");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioRolId"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("UsuarioRolId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique();

                    b.ToTable("usuario_roles", "seguridad");
                });

            modelBuilder.Entity("Termales.Entities.Models.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServicioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("ServicioId");

                    b.ToTable("Servicios", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Tienda.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("----")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<decimal>("PrecioCompra")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_compra");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock");

                    b.HasKey("ProductoId");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasFilter("codigo_barras IS NOT NULL");

                    b.ToTable("productos", "tienda");
                });

            modelBuilder.Entity("Termales.Entities.Models.TipoServicio", b =>
                {
                    b.Property<int>("TipoServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipo_servicio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoServicioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_maxima");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioPorPersona")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_por_persona");

                    b.HasKey("TipoServicioId");

                    b.ToTable("tipo_servicios", "public");

                    b.HasData(
                        new
                        {
                            TipoServicioId = 1,
                            Activo = true,
                            CapacidadMaxima = 50,
                            Descripcion = "Acceso a piscina termal",
                            Nombre = "Piscina",
                            PrecioPorPersona = 15.00m
                        },
                        new
                        {
                            TipoServicioId = 2,
                            Activo = true,
                            CapacidadMaxima = 4,
                            Descripcion = "Baño privado con agua termal",
                            Nombre = "Baño Privado",
                            PrecioPorPersona = 25.00m
                        });
                });

            modelBuilder.Entity("Termales.Entities.Models.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("turno_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TurnoId"));

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_personas");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("integer")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_total");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_servicio_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("TurnoId");

                    b.HasIndex("TipoServicioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("turnos", "public");
                });

            modelBuilder.Entity("Termales.Entities.Models.Aforo", b =>
                {
                    b.HasOne("Termales.Entities.Models.TipoServicio", "TipoServicio")
                        .WithMany("Aforos")
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.ItemMenu", b =>
                {
                    b.HasOne("Termales.Entities.Models.Comedor.CategoriaMenu", "Categoria")
                        .WithMany("Items")
                        .HasForeignKey("CategoriaMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.Orden", b =>
                {
                    b.HasOne("Termales.Entities.Models.Comedor.Mesa", "Mesa")
                        .WithMany("Ordenes")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Termales.Entities.Models.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.OrdenDetalle", b =>
                {
                    b.HasOne("Termales.Entities.Models.Comedor.ItemMenu", "ItemMenu")
                        .WithMany("OrdenDetalles")
                        .HasForeignKey("ItemMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Termales.Entities.Models.Comedor.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMenu");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Termales.Entities.Models.Inventario.EntradaInsumo", b =>
                {
                    b.HasOne("Termales.Entities.Models.Inventario.Insumo", "Insumo")
                        .WithMany("Entradas")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("Termales.Entities.Models.Inventario.EntradaProducto", b =>
                {
                    b.HasOne("Termales.Entities.Models.Tienda.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Termales.Entities.Models.Inventario.SalidaInsumo", b =>
                {
                    b.HasOne("Termales.Entities.Models.Inventario.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("Termales.Entities.Models.Pago", b =>
                {
                    b.HasOne("Termales.Entities.Models.Reserva", "Reserva")
                        .WithOne("Pago")
                        .HasForeignKey("Termales.Entities.Models.Pago", "ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Termales.Entities.Models.Reserva", b =>
                {
                    b.HasOne("Termales.Entities.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Termales.Entities.Models.Piscina", "Piscina")
                        .WithMany("Reservas")
                        .HasForeignKey("PiscinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Piscina");
                });

            modelBuilder.Entity("Termales.Entities.Models.ReservaServicio", b =>
                {
                    b.HasOne("Termales.Entities.Models.Reserva", "Reserva")
                        .WithMany("ReservaServicios")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Termales.Entities.Models.Servicio", "Servicio")
                        .WithMany("ReservaServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.Usuario", b =>
                {
                    b.HasOne("Termales.Entities.Models.Seguridad.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.UsuarioRol", b =>
                {
                    b.HasOne("Termales.Entities.Models.Seguridad.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Termales.Entities.Models.Seguridad.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Termales.Entities.Models.Turno", b =>
                {
                    b.HasOne("Termales.Entities.Models.TipoServicio", "TipoServicio")
                        .WithMany("Turnos")
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Termales.Entities.Models.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoServicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Termales.Entities.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.CategoriaMenu", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.ItemMenu", b =>
                {
                    b.Navigation("OrdenDetalles");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.Mesa", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("Termales.Entities.Models.Comedor.Orden", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Termales.Entities.Models.Inventario.Insumo", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("Termales.Entities.Models.Piscina", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Termales.Entities.Models.Reserva", b =>
                {
                    b.Navigation("Pago");

                    b.Navigation("ReservaServicios");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Termales.Entities.Models.Seguridad.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Termales.Entities.Models.Servicio", b =>
                {
                    b.Navigation("ReservaServicios");
                });

            modelBuilder.Entity("Termales.Entities.Models.TipoServicio", b =>
                {
                    b.Navigation("Aforos");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
